DELIMITER $$
CREATE FUNCTION quantidade_musicas_no_historico(ID INT)
RETURNS INT READS SQL DATA
BEGIN
  DECLARE total INT;
SELECT COUNT(NOME) FROM SpotifyClone.USUARIOS AS U
INNER JOIN SpotifyClone.HISTORICOS AS H ON U.USUARIO_ID = H.USUARIO_ID
WHERE U.USUARIO_ID = ID INTO total;
  RETURN total;
END $$
DELIMITER ;
