CREATE VIEW `cancoes_premium` AS
SELECT
  c.CANCAO AS `nome`,
  COUNT(h.ID_CANCAO) AS `reproducoes`
FROM
  HISTORICO_DE_REPRODUCAO AS h
  JOIN USUARIOS AS u ON u.ID_USUARIO = h.ID_USUARIO
  JOIN CANCOES AS c ON c.ID_CANCAO = h.ID_CANCAO
WHERE
  u.ID_PLANO <> 1
GROUP BY
  1
ORDER BY
  1;
