SELECT NOME AS 'artistas',
COUNT(*) AS 'seguidores' FROM SpotifyClone.SEGUINDO_ARTISTA AS S
INNER JOIN SpotifyClone.ARTISTAS AS A ON A.ARTISTA_ID = S.ARTISTA_ID
GROUP BY NOME ORDER BY 2 DESC, 1 LIMIT 3;
