DELIMITER $$
CREATE PROCEDURE albuns_do_artista(in n varchar(20))
BEGIN
SELECT NOME AS 'artista', NOME_ALBUM AS 'album' FROM SpotifyClone.ARTISTAS AS A
INNER JOIN SpotifyClone.ALBUNS AS B ON A.ARTISTA_ID = B.ARTISTA_ID
WHERE NOME = n;
END $$
DELIMITER ;
