CREATE VIEW historico_reproducao_usuarios AS 
SELECT USERS.NAME AS usuario,
SONGS.SONG_NAME AS nome
FROM SpotifyClone.USERS
INNER JOIN SpotifyClone.USER_HISTORY ON USER_HISTORY.USER_ID = USERS.USER_ID
INNER JOIN SpotifyClone.SONGS ON SONGS.SONG_ID = USER_HISTORY.SONG_ID
ORDER BY USERS.NAME, SONGS.SONG_NAME;
