DELIMITER $$
CREATE FUNCTION quantidade_musicas_no_historico(n varchar(30))
RETURNS INT READS SQL DATA
BEGIN
DECLARE total INT;
SELECT COUNT(*) FROM SpotifyClone.USUARIOS AS U
INNER JOIN SpotifyClone.HISTORICOS AS H ON U.USUARIO_ID = H.USUARIO_ID
WHERE NOME = n INTO total;
RETURN total;
END $$
DELIMITER;
