CREATE VIEW cancoes_premium AS
SELECT
SONG_NAME AS nome,
COUNT(H.USER_ID) AS reproducoes
FROM SpotifyClone.SONGS
INNER JOIN SpotifyClone.USER_HISTORY AS H ON H.SONG_ID = SONGS.SONG_ID
INNER JOIN SpotifyClone.USERS ON USERS.USER_ID = H.USER_ID
WHERE USERS.PLAN_ID != 1 
GROUP BY SONG_NAME
ORDER BY SONG_NAME;
