CREATE VIEW perfil_artistas AS 
SELECT 
ARTIST_NAME AS artista,
ALBUMS.ALBUM_NAME AS album,
COUNT(FOLLOW.USER_ID) AS seguidores
FROM SpotifyClone.ARTISTS
INNER JOIN SpotifyClone.ALBUMS ON ALBUMS.ARTIST_ID = ARTISTS.ARTIST_ID
INNER JOIN SpotifyClone.FOLLOW ON FOLLOW.ARTIST_ID = ARTISTS.ARTIST_ID
GROUP BY artista, album
ORDER BY seguidores DESC, artista, album;
