USE SpotifyClone;
CREATE VIEW perfil_artistas AS
SELECT (SELECT NOME FROM SpotifyClone.ARTISTAS AS A
WHERE A.ARTISTA_ID = B.ARTISTA_ID) AS 'artista', B.NOME_ALBUM AS 'album',
(SELECT COUNT(*) FROM SpotifyClone.SEGUINDO_ARTISTA AS S
WHERE B.ARTISTA_ID = S.ARTISTA_ID) AS 'seguidores' FROM SpotifyClone.ALBUNS AS B
ORDER BY 3 DESC, 1, 2;