SELECT M.NOME AS 'nome', COUNT(*) AS 'reproducoes' FROM SpotifyClone.USUARIOS AS U
INNER JOIN SpotifyClone.HISTORICOS AS H ON U.USUARIO_ID = H.USUARIO_ID
INNER JOIN SpotifyClone.PLANOS AS P ON P.PLANO_ID = U.PLANO_ID
INNER JOIN SpotifyClone.MUSICAS AS M ON M.MUSICA_ID = H.MUSICA_ID
WHERE TYPO IN('FAMILIAR', 'UNIVERSITÁRIO')
GROUP BY M.NOME ORDER BY 1;
