CREATE VIEW top_2_hits_do_momento AS
SELECT NOME AS 'cancao',
COUNT(*) AS 'reproducoes' FROM SpotifyClone.HISTORICOS AS H
INNER JOIN SpotifyClone.MUSICAS AS M ON H.MUSICA_ID = M.MUSICA_ID
GROUP BY NOME ORDER BY 2 DESC, 1 LIMIT 2;
