DELIMITER $$
CREATE TRIGGER trigger_usuario_delete
BEFORE DELETE ON USERS
FOR EACH ROW
BEGIN
DELETE FROM SpotifyClone.USER_HISTORY AS h
WHERE h.USER_ID = OLD.USER_ID;
DELETE FROM SpotifyClone.FOLLOW AS f
WHERE f.USER_ID = OLD.USER_ID;
END $$
DELIMITER ;
