CREATE VIEW top_2_hits_do_momento AS
SELECT 
SONG_NAME AS cancao,
COUNT(USER_HISTORY.USER_ID) AS reproducoes
FROM SpotifyClone.SONGS
INNER JOIN SpotifyClone.USER_HISTORY ON USER_HISTORY.SONG_ID = SONGS.SONG_ID
GROUP BY cancao
ORDER BY reproducoes DESC, SONG_NAME LIMIT 2;
