-- MySQL Script generated by MySQL Workbench
-- seg 31 mai 2021 23:49:44
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema SpotifyClone
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema SpotifyClone
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `SpotifyClone` ;
USE `SpotifyClone` ;

-- -----------------------------------------------------
-- Table `SpotifyClone`.`planos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SpotifyClone`.`planos` (
  `id_plano` INT NOT NULL AUTO_INCREMENT,
  `planoscol` VARCHAR(45) NULL,
  `preco_plano` DOUBLE NOT NULL,
  PRIMARY KEY (`id_plano`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SpotifyClone`.`usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SpotifyClone`.`usuarios` (
  `id_usuario` INT NOT NULL AUTO_INCREMENT,
  `usuarioscol` VARCHAR(45) NOT NULL,
  `idade_usuario` INT NOT NULL,
  `planos_id_plano` INT NOT NULL,
  PRIMARY KEY (`id_usuario`, `planos_id_plano`),
  INDEX `fk_usuarios_planos_idx` (`planos_id_plano` ASC) VISIBLE,
  CONSTRAINT `fk_usuarios_planos`
    FOREIGN KEY (`planos_id_plano`)
    REFERENCES `SpotifyClone`.`planos` (`id_plano`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SpotifyClone`.`artistas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SpotifyClone`.`artistas` (
  `id_artista` INT NOT NULL AUTO_INCREMENT,
  `nome_artista` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_artista`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SpotifyClone`.`albuns`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SpotifyClone`.`albuns` (
  `id_album` INT NOT NULL AUTO_INCREMENT,
  `albunscol` VARCHAR(150) NOT NULL,
  `artistas_id_artista` INT NOT NULL,
  PRIMARY KEY (`id_album`, `artistas_id_artista`),
  INDEX `fk_albuns_artistas1_idx` (`artistas_id_artista` ASC) VISIBLE,
  CONSTRAINT `fk_albuns_artistas1`
    FOREIGN KEY (`artistas_id_artista`)
    REFERENCES `SpotifyClone`.`artistas` (`id_artista`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SpotifyClone`.`musicas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SpotifyClone`.`musicas` (
  `id_musica` INT NOT NULL AUTO_INCREMENT,
  `nome_musica` VARCHAR(150) NOT NULL,
  `albuns_id_album` INT NOT NULL,
  `albuns_artistas_id_artista` INT NOT NULL,
  PRIMARY KEY (`id_musica`, `albuns_id_album`, `albuns_artistas_id_artista`),
  INDEX `fk_musicas_albuns1_idx` (`albuns_id_album` ASC, `albuns_artistas_id_artista` ASC) VISIBLE,
  CONSTRAINT `fk_musicas_albuns1`
    FOREIGN KEY (`albuns_id_album` , `albuns_artistas_id_artista`)
    REFERENCES `SpotifyClone`.`albuns` (`id_album` , `artistas_id_artista`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SpotifyClone`.`historico`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SpotifyClone`.`historico` (
  `usuarios_id_usuario` INT NOT NULL,
  `usuarios_planos_id_plano` INT NOT NULL,
  `musicas_id_musica` INT NOT NULL,
  `musicas_albuns_id_album` INT NOT NULL,
  `musicas_albuns_artistas_id_artista` INT NOT NULL,
  PRIMARY KEY (`usuarios_id_usuario`, `usuarios_planos_id_plano`, `musicas_id_musica`, `musicas_albuns_id_album`, `musicas_albuns_artistas_id_artista`),
  INDEX `fk_historico_musicas1_idx` (`musicas_id_musica` ASC, `musicas_albuns_id_album` ASC, `musicas_albuns_artistas_id_artista` ASC) VISIBLE,
  CONSTRAINT `fk_historico_usuarios1`
    FOREIGN KEY (`usuarios_id_usuario` , `usuarios_planos_id_plano`)
    REFERENCES `SpotifyClone`.`usuarios` (`id_usuario` , `planos_id_plano`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_historico_musicas1`
    FOREIGN KEY (`musicas_id_musica` , `musicas_albuns_id_album` , `musicas_albuns_artistas_id_artista`)
    REFERENCES `SpotifyClone`.`musicas` (`id_musica` , `albuns_id_album` , `albuns_artistas_id_artista`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SpotifyClone`.`seguindo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SpotifyClone`.`seguindo` (
  `usuarios_id_usuario` INT NOT NULL,
  `usuarios_planos_id_plano` INT NOT NULL,
  `artistas_id_artista` INT NOT NULL,
  PRIMARY KEY (`usuarios_id_usuario`, `usuarios_planos_id_plano`, `artistas_id_artista`),
  INDEX `fk_seguindo_artistas1_idx` (`artistas_id_artista` ASC) VISIBLE,
  CONSTRAINT `fk_seguindo_usuarios1`
    FOREIGN KEY (`usuarios_id_usuario` , `usuarios_planos_id_plano`)
    REFERENCES `SpotifyClone`.`usuarios` (`id_usuario` , `planos_id_plano`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_seguindo_artistas1`
    FOREIGN KEY (`artistas_id_artista`)
    REFERENCES `SpotifyClone`.`artistas` (`id_artista`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
